/** ظلّ معماري هادئ: صفحة تعريف عملية تشرح المنهج دون اختلاق تاريخ أو أرقام أو شهادات. */
import { Check, Compass, Layers3, Scale } from "lucide-react";
import { ButtonLink, PageHero, SectionIntro } from "@/components/SiteShell";
import { brandAssets } from "@/data/services";
import { usePageMeta } from "@/lib/seo";
import { DirectContactActions } from "@/lib/contact";

export default function About() {
  usePageMeta("عن الشركة", "تعرف على نهج شركة العزيزية للمظلات والسواتر في تخطيط حلول الظل والخصوصية والتغطيات الخارجية.", "/about");
  return <><PageHero eyebrow="عن الشركة" title="نهج عملي لتجهيز المساحات الخارجية." description="تجمع خدمات العزيزية بين المظلات والسواتر والبرجولات والتغطيات في حلول تبدأ من الموقع وطريقة الاستخدام." image={brandAssets.architecture} imageSrcSet={brandAssets.architectureSrcSet} /><section className="section about-statement"><div className="container about-statement__layout"><div><p className="eyebrow">فلسفة العمل</p><h2>الراحة الخارجية تحتاج أكثر من عنصر واحد.</h2></div><div><p>المظلة، البرجولة، الساتر، أو التغطية ليست مجرد إضافة منفصلة. قيمتها الحقيقية تظهر عندما تُرتب مع المساحة ومسار الحركة والخصوصية والضوء في تصور واحد.</p><p>لهذا تقدم الشركة كتالوج خدمات متخصصة يساعد على اختيار نقطة البداية الأنسب، ثم ربط التفاصيل بما يحتاجه الموقع فعليًا.</p><ButtonLink href="/services" tone="dark">استكشف الخدمات</ButtonLink></div></div></section><section className="section section--dark"><div className="container"><SectionIntro eyebrow="المبادئ" title="ثلاثة معايير تحكم القرار." /><div className="principle-grid"><article><Compass /><h3>نبدأ من الموقع</h3><p>الاستخدام الفعلي للمكان هو ما يقود الاختيار، لا المظهر وحده.</p></article><article><Layers3 /><h3>نربط العناصر</h3><p>الظل والخصوصية والجلوس والتغطية تتكامل ضمن مسار واحد للمساحة.</p></article><article><Scale /><h3>نوازن التفاصيل</h3><p>نوازن بين الخامة والهيكل والضوء لتبقى النتيجة عملية ومقروءة بصريًا.</p></article></div></div></section><section className="section material-section material-section--reverse"><div className="container material-section__layout"><div className="material-section__image"><img src={brandAssets.materials} alt="تفاصيل خامة وهيكل مظلة" /><span>تفاصيل تصنع الفرق</span></div><div className="material-section__copy"><p className="eyebrow">من الفكرة إلى القرار</p><h2>نحوّل السؤال العام إلى نقطة بداية واضحة.</h2><p>يمكنك إرسال صورة للموقع أو الاتصال مباشرة لتحديد الخدمة الأقرب إلى احتياج المساحة.</p><ul>{["نوع الاستخدام اليومي للمكان", "المساحة التقريبية واتجاه الشمس", "الحاجة إلى ظل أو خصوصية أو تغطية"].map((item) => <li key={item}><Check /><span>{item}</span></li>)}</ul><DirectContactActions /></div></div></section></>;
}
